#! /bin/sh

sxhkd &
picom &
~/.config/polybar/launch.sh &

bspc monitor HDMI-1-1 -d I II III IV V
bspc monitor eDP-1-1 -d VI VII VIII IX X

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio 0.50
bspc config focus_follows_pointer false
bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen true
bspc config center_pseudo_tiled true
bspc config honor_size_hints false

bspc config focused_border_color "#ba831e"

bspc config border_width 3
bspc config window_gap 8
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 27
bspc config left_padding 0

bspc config borderless_monocle true
bspc config gapless_monocle true
bscp config single_monocle false
bscp config top_monocle_padding 0
bspc config right_monocle_padding 0
bspc config bottom_monocle_padding 0
bspc config left_monocle_padding 0

