#!/bin/bash
DIR=$(readlink -f "$(dirname "$0")")
INSTALLATION="$HOME/.dfiles"
BRANCH="installation"

cd "$INSTALLATION" || exit 1

for d in $(ls -d */); do
  dir=$(echo "$d" | head -c -2)
  stow -t "$HOME" -D "$dir"
done

cd "$DIR" || exit 1

git worktree remove "$INSTALLATION" && rm -rf "$INSTALLATION"

