#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

DIR=$(readlink -f "$(dirname "$0")")
INSTALLATION="$HOME/.dfiles"

cd "$INSTALLATION" || exit 1

stow -t "$HOME" -D "configs"

cd "$DIR" || exit 1

git worktree remove "$INSTALLATION" && rm -rf "$INSTALLATION"
