#!/bin/bash
DIR=$(readlink -f "$(dirname "$0")")
INSTALLATION="$HOME/.dfiles"

cd "$INSTALLATION" || exit 1

for package in $(fd --type d --max-depth=1 --exclude "colorschemes"); do
  stow -t "$HOME" -D "$package"
done

cd "$DIR" || exit 1

git worktree remove "$INSTALLATION" && rm -rf "$INSTALLATION"

