#!/bin/bash
INSTALLATION="$HOME/.dfiles"
BRANCH="installation"

cd "$INSTALLATION" || exit 1

for dir in $(ls -d */); do
  package=$(echo "$dir" | head -c -2)
  package_dirs=$(find "$package" ! -path "$package" -type d | sed "s|^$package/|$HOME/|" | uniq | sort)
  if [[ -n "$package_dirs" ]]; then
    echo $package_dirs | xargs mkdir -p
  fi

  stow -t "$HOME" -S "$package"
done

