#!/bin/bash
DIR=$(readlink -f "$(dirname "$0")")
DOTFILES_ROOT=$(dirname "$DIR")

success() {
  # shellcheck disable=SC2059
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

delete_file() {
  if [ -e "$1" ]; then
    rm "$1"
    success "deleted $1"
  fi
  success "skipped $1"
}

find -H "${DOTFILES_ROOT}/home" -maxdepth 5 |
  while read -r src; do
    if [[ -f $src ]]; then
      path=${src#"${DOTFILES_ROOT}/home"/}
      dst="$HOME/${path}"
      mkdir -p "$(dirname "$dst")"
      delete_file "$dst"
    fi
  done
